# -*- coding: utf-8 -*-
"""DownSample-Block.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yUzL5908IriAE0c7tqRA6Svidw1C0eJi
"""

from keras.layers import *
from tensorflow_addons.layers import GroupNormalization

def Downsample(input_,level,groups):
  x1 = Conv3D(filters=128*level,kernel_size=(3,3,3),strides=(2,2,2),padding = 'same')(input_)
  x1 = GroupNormalization(groups)(x1)
  x2 = Conv3D(filters=128*level,kernel_size=(3,3,3),strides=(2,2,2),padding='same')(input_)
  x2 = GroupNormalization(groups)(x2)
  x = Concatenate()([x1,x2])
  x = Activation(swish)(x)
  return x